{% set version = "0.6.17" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: pytorch_sparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/torch_sparse/torch_sparse-{{ version }}.tar.gz
  sha256: 06e268dd77f73eb641da8f9383306d7afac6423383c9197b9df120955e2a96bd

build:
  number: 3
  skip: true  # [win]
  # as of pytorch 1.13, conda-forge only builds for CUDA 11.2+, see
  # https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3491
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pytorch                                # [build_platform != target_platform]
    - pytorch =*={{ torch_proc_type }}*      # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    - setuptools
    - pytest-runner
    - scipy
  run:
    - python
    # Use the run_export to depend on pytorch
    # - pytorch 
    - pytest
    - pytest-cov
    - scipy
    - pytorch_scatter
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - torch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_sparse

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - mikemhenry
    - h-vetinari
