{% set name = "torch_sparse" %}
{% set version = "0.6.3" %}

{% set pytorch_sparse_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [linux or win]
{% set pytorch_sparse_proc_type = "cpu" %}                                                # [osx]

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d2bb488e14207187f9856d2a9349851e7a3cc37d0f5cf7c7ed930d0fc8c7531

build:
  number: 0
  skip: true  # [win]

outputs:
  # A meta-package to select CPU or GPU pytorch_sparse build.
  - name: pytorch_sparse_proc
    version: 1.0.0
    build:
      number: 0
      string: {{ pytorch_sparse_proc_type }}
    test:
      commands:
        - exit 0

  - name: pytorch_sparse
    version: {{ version }}
    build:
      number: 0
      script: 
        - export USE_STATIC_CUDNN="1"  # [linux and cuda_compiler_version != "None"]
        - export USE_STATIC_NCCL="1"   # [linux and cuda_compiler_version != "None"]
        - export FORCE_CUDA="1"        # [linux and cuda_compiler_version != "None"]
        - python -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [linux and cuda_compiler_version != "None"]
      host:
        - python
        - pytorch
        - setuptools
        - scipy
        - pytest-runner
        - pip
      run:
        - python
        - pytorch
      run_constrained:
        - pytorch_sparse_proc * {{ pytorch_sparse_proc_type }}
    test:
      requires:
        - pytest
        - pytest-cov
      imports:
        - torch_sparse
    about:
      home: https://github.com/rusty1s/pytorch_sparse
      summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
      license: MIT
      license_file: LICENSE
      dev_url: https://github.com/rusty1s/pytorch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_sparse

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
