{% set name = "torch_sparse" %}
{% set version = "0.6.6" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ee9e76eb2ef144afb82ae512ee768e652c436a38f92e7b90e7d0aa3c6c2814e

build:
  number: 0
  skip: true  # [win or cuda_compiler_version == 'None' or cuda_compiler_version == '10.2']
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version != 'None']
    - export CC="$GCC"   # [linux64 and cuda_compiler_version != 'None']
    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - setuptools
    - scipy
    - pytest-runner
    - pip
  run:
    - python
    - pytorch
    - pytorch_scatter
    - scipy
    - pytest
    - pytest-cov

test:
  imports:
    - torch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_sparse

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
